# Generated by Django 5.1.6 on 2025-03-13 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.branch'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='service',
            name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'service', 'branch', 'booking_datetime')},
        ),
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ManyToManyField(to='booking.branch'),
        ),
    ]
