# Generated by Django 5.1.6 on 2025-04-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_page_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/defaults/default.jpg', upload_to='uploads/blog-thumbnails/'),
        ),
    ]
